spring:
  application:
    name: tseurekaserver
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true

server:
  port: 8761

logging:
  level:
    com.netflix.eureka: DEBUG
