version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Pass@123
      MYSQL_DATABASE: Furnishit
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  eurekaserver:
    build:
      context: ./Backend/tseurekaserver
      dockerfile: Dockerfile
    container_name: eurekaserver
    ports:
      - "8761:8761"
    networks:
      - backend

  user-service:
    build:
      context: ./Backend/user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Furnishit
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Pass@123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
    depends_on:
      - mysql
      - eurekaserver
    networks:
      - backend

  designer-service:
    build:
      context: ./Backend/designer-service
      dockerfile: Dockerfile
    container_name: designer-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Furnishit?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Pass@123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
    depends_on:
      - mysql
      - eurekaserver
      - user-service
    networks:
      - backend

  booking-service:
    build:
      context: ./Backend/booking-service
      dockerfile: Dockerfile
    container_name: booking-service
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Furnishit
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Pass@123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
    depends_on:
      - mysql
      - eurekaserver
      - user-service
      - designer-service
    networks:
      - backend

  customer-service:
    build:
      context: ./Backend/customer-service
      dockerfile: Dockerfile
    container_name: customer-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Furnishit
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Pass@123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
    depends_on:
      - mysql
      - eurekaserver
    networks:
      - backend

  frontend:
    build:
      context: ./Frontend/capstone-pro2-master
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - designer-service
      - customer-service
      - booking-service
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
